import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { getValidGoogleToken } from '@/services/auth/oauth';
import { verifySignatureAppRouter } from '@upstash/qstash/nextjs';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function handler(req: Request) {
  try {
    const body = await req.json();
    const { scanId, userId, threadIds, isLastChunk } = body;
    
    if (!scanId || !userId || !threadIds || !Array.isArray(threadIds)) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const accessToken = await getValidGoogleToken(supabase, userId, 'gmail');
    if (!accessToken) {
      return NextResponse.json({ error: 'Gmail token invalid' }, { status: 401 });
    }

    const profileRes = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/profile', {
      headers: { Authorization: `Bearer ${accessToken}` }
    });
    const profileData = await profileRes.json();
    const userEmail = profileData.emailAddress?.toLowerCase();

    const allEligibleThreads = [];
    let skippedBulk = 0;
    let skippedEmpty = 0;
    let threadsEligible = 0;

    // Fetch full threads and filter
    const chunkPromises = threadIds.map(async (id) => {
      const res = await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/threads/${id}?format=full`, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      if (!res.ok) return null;
      return res.json();
    });

    const threadDetails = await Promise.all(chunkPromises);

    for (const t of threadDetails) {
      if (!t || !t.messages) continue;

      let isBulk = false;
      const normalizedMessages = [];

      for (const msg of t.messages) {
        const headers = msg.payload?.headers || [];
        const getHeader = (name: string) => headers.find((h: any) => h.name.toLowerCase() === name.toLowerCase())?.value;
        
        if (getHeader('list-unsubscribe') || getHeader('x-autogenerated') || getHeader('x-calendar-event')) {
          isBulk = true;
          break;
        }

        const from = getHeader('from') || '';
        const to = getHeader('to') || '';
        const subject = getHeader('subject') || '';
        const dateStr = getHeader('date') || msg.internalDate;
        const timestamp = new Date(msg.internalDate ? Number(msg.internalDate) : dateStr).toISOString();

        const direction = from.toLowerCase().includes(userEmail) ? 'outbound' : 'inbound';
        const content = msg.snippet || '';

        normalizedMessages.push({
          message_id: msg.id,
          from,
          to,
          subject,
          timestamp,
          direction,
          content
        });
      }

      if (isBulk) {
        skippedBulk++;
        continue;
      }
      if (normalizedMessages.length === 0) {
        skippedEmpty++;
        continue;
      }

      allEligibleThreads.push({
        scan_id: scanId,
        thread_id: t.id,
        evidence: { _raw_transcript: normalizedMessages },
        created_at: new Date().toISOString()
      });
      threadsEligible++;
    }

    if (allEligibleThreads.length > 0) {
      const { error: insertError } = await supabase
        .from('leak_scan_threads')
        .insert(allEligibleThreads);
      if (insertError) console.error('Thread insert error:', insertError);
    }

    // If this is the last chunk, trigger the detect route via QStash
    if (isLastChunk) {
        console.log(`[Ingest Worker] Last chunk processed for scan ${scanId}. Triggering detection...`);
        const { Client } = await import('@upstash/qstash');
        const qstashToken = process.env.QSTASH_TOKEN || 'dummy_token'; 
        const qstash = new Client({ token: qstashToken });
        
        const baseUrl = process.env.NEXT_PUBLIC_APP_URL || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000');
        await qstash.publishJSON({
          url: `${baseUrl}/api/revenue/detect`,
          body: { scan_id: scanId },
          headers: {
            'Authorization': `Bearer ${process.env.CRON_SECRET}`
          }
        });
    }

    return NextResponse.json({ success: true, processed: threadIds.length, threadsEligible });
  } catch (err: any) {
    console.error('[Ingest Worker Error]:', err);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

export const POST = verifySignatureAppRouter(handler);
